apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: esocregistry.azurecr.io/azvote/azure-vote-front
    newTag: 4b3f91e3a7b7ae8ce7f21ce76aead3a72854e74d
  - name: esocregistry.azurecr.io/azvote/azure-vote-back
    newTag: 4b3f91e3a7b7ae8ce7f21ce76aead3a72854e74d
resources:
  - manifests.yaml