apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: esocregistry.azurecr.io/azure-vote-front
    newTag: cc9f021cf364e3f28ad491ec87e9a3c2483c9dbf
  - name: esocregistry.azurecr.io/azure-vote-back
    newTag: cc9f021cf364e3f28ad491ec87e9a3c2483c9dbf
resources:
  - manifests.yaml